before:
  hooks:
    - go mod download

builds:
- env:
  - CGO_ENABLED=0

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brews:
  -
    name: dots
    github:
      owner: mitinarseny
      name: homebrew-tap
    commit_author:
      name: Arseny Mitin
      email: mitinarseny@gmail.com
    folder: Formula
    homepage: "https://github.com/mitinarseny/dots"
    description: "Delivery tool for dotfiles"